apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: d_svc
  name: d_svc
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    app: v
  type: NodePort
status:
  loadBalancer: {}
