apiVersion: apps/v
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v
  name: v
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v
      rel: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v
        rel: blue
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
