apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    v: green
  name: dp
spec:
  replicas: 2
  selector:
    matchLabels:
      v: red
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        v: red
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
