apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    v: green
  name: dp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 200
  selector:
    v: green
status:
  loadBalancer: {}
