apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: v
  name: v
spec:
  replicas: 2
  selector:
    matchLabels:
      app: v
      rel: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: v
        rel: green
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
